# I learned a lot from: https://github.com/hi4th/kernel_oneplus_sm8150 and https://github.com/midozalouk/android_kernel_oneplus_sm8150
name: ✅Build KernelSU (v0.9.5) with SusFS
on:
  workflow_dispatch:
    inputs:
      kernel_source_url:
        description: 'URL of the kernel source repository'
        required: true
        default: 'https://github.com/yaap/kernel_oneplus_sm8150'
      kernel_branch:
        description: 'Branch of the kernel source'
        required: true
        default: 'sixteen'
      kernel_defconfig:
        description: 'defconfig file to use'
        required: true
        default: 'gulch_defconfig'
      clang_commit:
        description: 'Clang commit to use'
        required: true
        default: 'r547379'
      clang_version:
        description: 'Pre-built Clang version'
        required: true
        default: '20'
      output_name:
        description: 'Name of the output.zip'
        required: true
        default: 'OnePlus-SM8150_YAAP-16_KernelSUv095_SusFS'
  schedule:
    # http://crontab.guru
    # Runs at 10:00 PM UTC, every Tuesday
    - cron: '0 22 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"

      KERNEL_SOURCE_URL: ${{ github.event.inputs.kernel_source_url || 'https://github.com/yaap/kernel_oneplus_sm8150' }}
      KERNEL_BRANCH: ${{ github.event.inputs.kernel_branch || 'sixteen' }}
      KERNEL_DEFCONFIG: ${{ github.event.inputs.kernel_defconfig || 'gulch_defconfig' }}
      
      # Clang commits here: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main
      # Clang version found at $CLANG_COMMIT/bin/clang-$CLANG_VERSION
      CLANG_COMMIT: ${{ github.event.inputs.clang_commit || 'r547379' }}
      CLANG_VERSION: ${{ github.event.inputs.clang_version || '20' }}

      KERNEL_CMDLINE: "CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip LLVM=1 LLVM_IAS=1 O=out"
      
      OUTPUT_ZIP_NAME: ${{ github.event.inputs.output_name || 'OnePlus-SM8150_YAAP-16_KernelSUv095_SusFS' }}
    steps:
    - name: 🛠️Set up ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: ☢️Remove unnecessary files
      run: |
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: ⬇️Install dependencies - Ubuntu APT packages
      run: |
        sudo apt-get update -y 
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install libelf-dev libarchive-tools lld llvm axel binutils make python3 libssl-dev build-essential bc bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y

    - name: ⬇️Install dependencies - AnyKernel3 (walkonbothsides fork for 'oneplus7' branch)
      run: |
        git clone https://github.com/walkonbothsides/AnyKernel3 -b oneplus7 --depth=1
        rm -rf AnyKernel3/.git

    - name: ⬇️Install dependencies - AOSP Clang
      run: |
        mkdir toolchains
        cd toolchains
        git clone --filter=blob:none --sparse -b main https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 aosp-clang
        cd aosp-clang
        git sparse-checkout set clang-${{ env.CLANG_COMMIT }}
        cd clang-${{ env.CLANG_COMMIT }}

    - name: 📝Clone kernel source
      run: |
        rm -rf kernel
        git clone --depth=1 --branch "${KERNEL_BRANCH}" "${KERNEL_SOURCE_URL}" kernel
        cd kernel
        git submodule update --init --recursive
        cd ..
      env:
        KERNEL_SOURCE_URL: ${{ env.KERNEL_SOURCE_URL }}
        KERNEL_BRANCH: ${{ env.KERNEL_BRANCH }}

    - name: ✍️Manually backport path_umount
      # More info about the path_umount.patch here: https://kernelsu.org/guide/how-to-integrate-for-non-gki.html#how-to-backport-path-umount
      run: |
        cd kernel && patch -p1 < kernelsu.patch
        wget https://raw.githubusercontent.com/ebears/OnePlus-SM8150-Kernel-Builds/refs/heads/main/patches/path_umount.patch
        patch -p1 < path_umount.patch
        cd ..

    - name: 🗣️Apply KernelSU with SusFS
      continue-on-error: true
      run: |
        cd kernel
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
        echo "CONFIG_KSU=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_PATH=n" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./arch/arm64/configs/${{ env.KERNEL_DEFCONFIG }}
        git clone --depth=1 --branch kernel-4.14 https://gitlab.com/simonpunk/susfs4ksu.git susfs4ksu
        cd susfs4ksu
        cp ./kernel_patches/fs/* ../fs/
        cp ./kernel_patches/include/linux/* ../include/linux/
        cd ../KernelSU
        wget https://raw.githubusercontent.com/ebears/OnePlus-SM8150-Kernel-Builds/refs/heads/main/patches/10_enable_susfs_for_ksu-for-kernelsu-v095.patch
        patch -p1 < 10_enable_susfs_for_ksu-for-kernelsu-v095.patch
        cd ..
        wget https://raw.githubusercontent.com/ebears/OnePlus-SM8150-Kernel-Builds/refs/heads/main/patches/50_add_susfs_in_kernel-for-kernel-4.14.patch
        patch -p1 < 50_add_susfs_in_kernel-for-kernel-4.14.patch
        cd ..

    #### ERROR HANDLING ####
    - name: 🛠️Check for patch errors
      run: |
        mkdir rej_files
        find . -name "*.rej" -exec cp {} rej_files/ \;

    - name: 📤Upload patch rejects
      uses: actions/upload-artifact@v4
      with:
        name: patch-rejects
        path: rej_files/
    #### END OF ERROR HANDLING ####

    - name: ℹ️Get KernelSU version
      id: get_version
      run: |
        cd kernel/KernelSU
        git rev-list --count HEAD
        echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        cd ../../

    - name: 🏗️Build kernel
      run: |
        export PATH=$(pwd)/toolchains/aosp-clang/clang-${CLANG_COMMIT}/bin/:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        export LD=ld.lld
        export BRAND_SHOW_FLAG=oneplus
        export TARGET_PRODUCT=msmnile
        cd kernel
        make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="ccache clang-${CLANG_VERSION}"
        make $KERNEL_CMDLINE scripts CC="ccache clang-${CLANG_VERSION}"
        make $KERNEL_CMDLINE prepare CC="ccache clang-${CLANG_VERSION}"
        make $KERNEL_CMDLINE CC="ccache clang-${CLANG_VERSION}" -j$(nproc --all)
        cp out/arch/arm64/boot/Image ../AnyKernel3
        cd ..

    - name: 🐕Get custom repo version
      id: get_repo_version
      run: |
        git clone https://github.com/ebears/OnePlus-SM8150-Kernel-Builds.git temp-repo
        cd temp-repo
        git rev-list --count HEAD
        DAY=$(date +%d)
        MONTH=$(date +%m)
        SUM=$((DAY + MONTH))
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "GENERATED_VERSION=${PRODUCT}${COMMIT_COUNT}" >> $GITHUB_OUTPUT
        cd ..

    - name: 💾Create AnyKernel3 zip
      run: |
        cd AnyKernel3
        zip -r ../${{ env.OUTPUT_ZIP_NAME }}-${{ steps.get_repo_version.outputs.GENERATED_VERSION }}.zip *
        cd ..

    - name: ☁️Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.OUTPUT_ZIP_NAME }}-${{ steps.get_repo_version.outputs.GENERATED_VERSION }}
        path: "AnyKernel3/*"
        retention-days: 7 # on artifacts, not releases
        overwrite: true
        
    - name: 📢Push to releases
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          ${{ env.OUTPUT_ZIP_NAME }}-${{ steps.get_repo_version.outputs.GENERATED_VERSION }}.zip
        name: "🕰️KernelSU (v0.9.5) with 🕵️SusFS - ${{ steps.get_repo_version.outputs.GENERATED_VERSION }}"
        tag_name: KernelSU-v0.9.5-SusFS-${{ steps.get_repo_version.outputs.GENERATED_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          📱**Device:** OnePlus SM8150\
          ⏱️**Target:** Android 16 (YAAP)

          📦APK: [KernelSU (v0.9.5)](https://github.com/tiann/KernelSU/releases/tag/v0.9.5)
          🗃️Module: [susfs4ksu-module](https://github.com/sidex15/susfs4ksu-module)
          
          <img src="https://i.imgur.com/nfpAazp.png" alt="amogus" width="45"/>

          Includes [SusFS](https://gitlab.com/simonpunk/susfs4ksu) support.\
          Based on [KernelSU](https://github.com/tiann/KernelSU/tree/v0.9.5) commit [${{ steps.get_version.outputs.VERSION }}](https://github.com/tiann/KernelSU/commit/${{ steps.get_version.outputs.VERSION }}).\
          Complied with [Clang ${{ env.CLANG_VERSION }}](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-${CLANG_COMMIT}/bin) using [GitHub Actions](https://github.com/ebears/OnePlus-SM8150-Kernel-Builds/actions).